version: "3"
services:
  mongo:
    image: mongo:latest
    hostname: "mongo"

  advicery:
    build: "."
    ports:
      - "8080:8080"
      - "2345:12345"
    environment:
      MONGO_HOST: "mongo"
    command: "./debug.sh"
    security_opt:
      - seccomp:unconfined
    depends_on:
      - mongo